// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"subflow-core-go/pkg/ent/predicate"
	"subflow-core-go/pkg/ent/task"
	"subflow-core-go/pkg/ent/workflow"
	"subflow-core-go/pkg/ent/workflownode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowUpdate is the builder for updating Workflow entities.
type WorkflowUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowMutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (wu *WorkflowUpdate) Where(ps ...predicate.Workflow) *WorkflowUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetName sets the "name" field.
func (wu *WorkflowUpdate) SetName(s string) *WorkflowUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetType sets the "type" field.
func (wu *WorkflowUpdate) SetType(i int) *WorkflowUpdate {
	wu.mutation.ResetType()
	wu.mutation.SetType(i)
	return wu
}

// AddType adds i to the "type" field.
func (wu *WorkflowUpdate) AddType(i int) *WorkflowUpdate {
	wu.mutation.AddType(i)
	return wu
}

// SetDesc sets the "desc" field.
func (wu *WorkflowUpdate) SetDesc(s string) *WorkflowUpdate {
	wu.mutation.SetDesc(s)
	return wu
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableDesc(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetDesc(*s)
	}
	return wu
}

// ClearDesc clears the value of the "desc" field.
func (wu *WorkflowUpdate) ClearDesc() *WorkflowUpdate {
	wu.mutation.ClearDesc()
	return wu
}

// AddWorkflowNodeIDs adds the "workflow_nodes" edge to the WorkflowNode entity by IDs.
func (wu *WorkflowUpdate) AddWorkflowNodeIDs(ids ...int) *WorkflowUpdate {
	wu.mutation.AddWorkflowNodeIDs(ids...)
	return wu
}

// AddWorkflowNodes adds the "workflow_nodes" edges to the WorkflowNode entity.
func (wu *WorkflowUpdate) AddWorkflowNodes(w ...*WorkflowNode) *WorkflowUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.AddWorkflowNodeIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (wu *WorkflowUpdate) AddTaskIDs(ids ...int) *WorkflowUpdate {
	wu.mutation.AddTaskIDs(ids...)
	return wu
}

// AddTasks adds the "tasks" edges to the Task entity.
func (wu *WorkflowUpdate) AddTasks(t ...*Task) *WorkflowUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wu.AddTaskIDs(ids...)
}

// Mutation returns the WorkflowMutation object of the builder.
func (wu *WorkflowUpdate) Mutation() *WorkflowMutation {
	return wu.mutation
}

// ClearWorkflowNodes clears all "workflow_nodes" edges to the WorkflowNode entity.
func (wu *WorkflowUpdate) ClearWorkflowNodes() *WorkflowUpdate {
	wu.mutation.ClearWorkflowNodes()
	return wu
}

// RemoveWorkflowNodeIDs removes the "workflow_nodes" edge to WorkflowNode entities by IDs.
func (wu *WorkflowUpdate) RemoveWorkflowNodeIDs(ids ...int) *WorkflowUpdate {
	wu.mutation.RemoveWorkflowNodeIDs(ids...)
	return wu
}

// RemoveWorkflowNodes removes "workflow_nodes" edges to WorkflowNode entities.
func (wu *WorkflowUpdate) RemoveWorkflowNodes(w ...*WorkflowNode) *WorkflowUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.RemoveWorkflowNodeIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (wu *WorkflowUpdate) ClearTasks() *WorkflowUpdate {
	wu.mutation.ClearTasks()
	return wu
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (wu *WorkflowUpdate) RemoveTaskIDs(ids ...int) *WorkflowUpdate {
	wu.mutation.RemoveTaskIDs(ids...)
	return wu
}

// RemoveTasks removes "tasks" edges to Task entities.
func (wu *WorkflowUpdate) RemoveTasks(t ...*Task) *WorkflowUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wu.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkflowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkflowUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkflowUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WorkflowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.GetType(); ok {
		_spec.SetField(workflow.FieldType, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedType(); ok {
		_spec.AddField(workflow.FieldType, field.TypeInt, value)
	}
	if value, ok := wu.mutation.Desc(); ok {
		_spec.SetField(workflow.FieldDesc, field.TypeString, value)
	}
	if wu.mutation.DescCleared() {
		_spec.ClearField(workflow.FieldDesc, field.TypeString)
	}
	if wu.mutation.WorkflowNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.WorkflowNodesTable,
			Columns: []string{workflow.WorkflowNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedWorkflowNodesIDs(); len(nodes) > 0 && !wu.mutation.WorkflowNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.WorkflowNodesTable,
			Columns: []string{workflow.WorkflowNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.WorkflowNodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.WorkflowNodesTable,
			Columns: []string{workflow.WorkflowNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedTasksIDs(); len(nodes) > 0 && !wu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkflowUpdateOne is the builder for updating a single Workflow entity.
type WorkflowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowMutation
}

// SetName sets the "name" field.
func (wuo *WorkflowUpdateOne) SetName(s string) *WorkflowUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetType sets the "type" field.
func (wuo *WorkflowUpdateOne) SetType(i int) *WorkflowUpdateOne {
	wuo.mutation.ResetType()
	wuo.mutation.SetType(i)
	return wuo
}

// AddType adds i to the "type" field.
func (wuo *WorkflowUpdateOne) AddType(i int) *WorkflowUpdateOne {
	wuo.mutation.AddType(i)
	return wuo
}

// SetDesc sets the "desc" field.
func (wuo *WorkflowUpdateOne) SetDesc(s string) *WorkflowUpdateOne {
	wuo.mutation.SetDesc(s)
	return wuo
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableDesc(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetDesc(*s)
	}
	return wuo
}

// ClearDesc clears the value of the "desc" field.
func (wuo *WorkflowUpdateOne) ClearDesc() *WorkflowUpdateOne {
	wuo.mutation.ClearDesc()
	return wuo
}

// AddWorkflowNodeIDs adds the "workflow_nodes" edge to the WorkflowNode entity by IDs.
func (wuo *WorkflowUpdateOne) AddWorkflowNodeIDs(ids ...int) *WorkflowUpdateOne {
	wuo.mutation.AddWorkflowNodeIDs(ids...)
	return wuo
}

// AddWorkflowNodes adds the "workflow_nodes" edges to the WorkflowNode entity.
func (wuo *WorkflowUpdateOne) AddWorkflowNodes(w ...*WorkflowNode) *WorkflowUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.AddWorkflowNodeIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (wuo *WorkflowUpdateOne) AddTaskIDs(ids ...int) *WorkflowUpdateOne {
	wuo.mutation.AddTaskIDs(ids...)
	return wuo
}

// AddTasks adds the "tasks" edges to the Task entity.
func (wuo *WorkflowUpdateOne) AddTasks(t ...*Task) *WorkflowUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wuo.AddTaskIDs(ids...)
}

// Mutation returns the WorkflowMutation object of the builder.
func (wuo *WorkflowUpdateOne) Mutation() *WorkflowMutation {
	return wuo.mutation
}

// ClearWorkflowNodes clears all "workflow_nodes" edges to the WorkflowNode entity.
func (wuo *WorkflowUpdateOne) ClearWorkflowNodes() *WorkflowUpdateOne {
	wuo.mutation.ClearWorkflowNodes()
	return wuo
}

// RemoveWorkflowNodeIDs removes the "workflow_nodes" edge to WorkflowNode entities by IDs.
func (wuo *WorkflowUpdateOne) RemoveWorkflowNodeIDs(ids ...int) *WorkflowUpdateOne {
	wuo.mutation.RemoveWorkflowNodeIDs(ids...)
	return wuo
}

// RemoveWorkflowNodes removes "workflow_nodes" edges to WorkflowNode entities.
func (wuo *WorkflowUpdateOne) RemoveWorkflowNodes(w ...*WorkflowNode) *WorkflowUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.RemoveWorkflowNodeIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (wuo *WorkflowUpdateOne) ClearTasks() *WorkflowUpdateOne {
	wuo.mutation.ClearTasks()
	return wuo
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (wuo *WorkflowUpdateOne) RemoveTaskIDs(ids ...int) *WorkflowUpdateOne {
	wuo.mutation.RemoveTaskIDs(ids...)
	return wuo
}

// RemoveTasks removes "tasks" edges to Task entities.
func (wuo *WorkflowUpdateOne) RemoveTasks(t ...*Task) *WorkflowUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return wuo.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (wuo *WorkflowUpdateOne) Where(ps ...predicate.Workflow) *WorkflowUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkflowUpdateOne) Select(field string, fields ...string) *WorkflowUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workflow entity.
func (wuo *WorkflowUpdateOne) Save(ctx context.Context) (*Workflow, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkflowUpdateOne) SaveX(ctx context.Context) *Workflow {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WorkflowUpdateOne) sqlSave(ctx context.Context) (_node *Workflow, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflow.FieldID)
		for _, f := range fields {
			if !workflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.GetType(); ok {
		_spec.SetField(workflow.FieldType, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedType(); ok {
		_spec.AddField(workflow.FieldType, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.Desc(); ok {
		_spec.SetField(workflow.FieldDesc, field.TypeString, value)
	}
	if wuo.mutation.DescCleared() {
		_spec.ClearField(workflow.FieldDesc, field.TypeString)
	}
	if wuo.mutation.WorkflowNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.WorkflowNodesTable,
			Columns: []string{workflow.WorkflowNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedWorkflowNodesIDs(); len(nodes) > 0 && !wuo.mutation.WorkflowNodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.WorkflowNodesTable,
			Columns: []string{workflow.WorkflowNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.WorkflowNodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.WorkflowNodesTable,
			Columns: []string{workflow.WorkflowNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedTasksIDs(); len(nodes) > 0 && !wuo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workflow{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
